name: Create production builds

jobs:
  # Build Android
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  # Build iOS
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production

  # Submit Android Build
  submit_android_build:
    name: Submit Android Build
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}

  # Submit iOS Build
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }} 